pages:
    stage: deploy
    script:
    - mkdir .public
    - mkdir .public/assets
    - cp -r assets/* .public/assets
    - cp -r assets/index.html .public
    - mv .public public
    artifacts:
        paths:
        - public
    only:
    - master