pages:
    stage: deploy
    script:
    - mkdir .public
    - cp -r template/* .public
    - cp -r *.html .public
    - cp -r js .public/
    - cp -r template-doc .public/
    - cp -r css .public/
    - cp -r fonts .public/
    - cp -r images .public/
    - mv .public public
    artifacts:
        paths:
        - public
    only:
    - master